# Generated by Django 5.2.9 on 2025-12-02 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField(default=4)),
                ('departure_date', models.DateField()),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='cities.city')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='cities.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['departure_date'],
                'constraints': [models.UniqueConstraint(fields=('id', 'departure_date'), name='car_unique_trip_per_day')],
            },
        ),
    ]
