# Generated by Django 5.2.9 on 2025-12-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='brand',
        ),
    ]
